### PR TITLE
controller: progpagate obj deletion to Gateways

### LINKED ISSUE #728: Gateway Controller not reconciled on AIGatewayRoute delete
*Description*:
When an AIGatewayRoute like llama3-temp is deleted, the filter-config secret and APIs like /v1/models are not updated. The deleted model (llama3-temp) still appears in the model list:

GET /v1/models 

```
{
  "data": [
    {
      "id": "llama3",
      "created": 1750244633,
      "object": "model",
      "owned_by": "internal-serving"
    },
    {
      "id": "llama3-temp",
      "created": 1750307402,
      "object": "model",
      "owned_by": "ai-gateway"
    }
  ],
  "object": "list"
}
```

Looking at the code, the issue seems to be that if the AIGatewayRoute is deleted, syncGateway is never called. There’s no mechanism for the gateway controller to detect and respond to route deletions:

```go
// Reconcile implements [reconcile.TypedReconciler].
func (c *AIGatewayRouteController) Reconcile(ctx context.Context, req reconcile.Request) (reconcile.Result, error) {
	c.logger.Info("Reconciling AIGatewayRoute", "namespace", req.Namespace, "name", req.Name)

	var aiGatewayRoute aigv1a1.AIGatewayRoute
	if err := c.client.Get(ctx, req.NamespacedName, &aiGatewayRoute); err != nil {
		if client.IgnoreNotFound(err) == nil {
			c.logger.Info("Deleting AIGatewayRoute",
				"namespace", req.Namespace, "name", req.Name) // Nothing is done to update gateway controller
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, err
	}

	if err := c.syncAIGatewayRoute(ctx, &aiGatewayRoute); err != nil { // Gateway Controller is only synced in this path
		c.logger.Error(err, "failed to sync AIGatewayRoute")
		c.updateAIGatewayRouteStatus(ctx, &aiGatewayRoute, aigv1a1.ConditionTypeNotAccepted, err.Error())
		return ctrl.Result{}, err
	}
	c.updateAIGatewayRouteStatus(ctx, &aiGatewayRoute, aigv1a1.ConditionTypeAccepted, "AI Gateway Route reconciled successfully")
	return reconcile.Result{}, nil
}

func (c *AIGatewayRouteController) syncGateways(ctx context.Context, aiGatewayRoute *aigv1a1.AIGatewayRoute) error {
	for _, t := range aiGatewayRoute.Spec.TargetRefs {
		var gw gwapiv1.Gateway
		if err := c.client.Get(ctx, client.ObjectKey{Name: string(t.Name), Namespace: aiGatewayRoute.Namespace}, &gw); err != nil {
			if apierrors.IsNotFound(err) {
				c.logger.Info("Gateway not found", "namespace", aiGatewayRoute.Namespace, "name", t.Name)
				continue
			}
			return fmt.Errorf("failed to get Gateway: %w", err)
		}
		c.logger.Info("syncing Gateway", "namespace", gw.Namespace, "name", gw.Name)
		c.gatewayEventChan <- event.GenericEvent{Object: &gw}
	}
	return nil
}

```

*Repro steps*:

1.	Create the following AIGatewayRoute
2.	Delete it

```yaml
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: llama3-temp
  namespace: test-ns
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: envoy-ai-gateway-internal
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: llama3-temp
      backendRefs:
        - name: llama3
          weight: 100
  llmRequestCosts:
    - metadataKey: llm_input_token
      type: InputToken # Counts tokens in the request
    - metadataKey: llm_output_token
      type: OutputToken # Counts tokens in the response
    - metadataKey: llm_total_token
      type: TotalToken # Tracks combined usage
```

*Environment*:
Using v0.2.1 ( https://github.com/envoyproxy/ai-gateway/releases/tag/v0.2.1 )

*Logs*:

```
2025-06-18 20:11:00.898Z 9:00 2025-06-18T11:11:00Z      INFO    controller.ai-gateway-route     Reconciling AIGatewayRoute      {"namespace": "test-ns", "name": "llama3-temp"}
2025-06-18 20:11:00.898Z 9:00 2025-06-18T11:11:00Z      INFO    controller.ai-gateway-route     Deleting AIGatewayRoute {"namespace": "test-ns", "name": "llama3-temp"}
2025-06-18 20:11:00.914Z 9:00 2025-06-18T11:11:00Z      INFO    controller.ai-gateway-route     Reconciling AIGatewayRoute      {"namespace": "test-ns", "name": "llama3-temp"}
2025-06-18 20:11:00.914Z 9:00 2025-06-18T11:11:00Z      INFO    controller.ai-gateway-route     Deleting AIGatewayRoute {"namespace": "test-ns", "name": "llama3-temp"}
2025-06-18 20:11:00.918Z 9:00 2025-06-18T11:11:00Z      INFO    envoy-gateway-extension-server  non-ai-gateway cluster name     {"cluster_name": "envoyextensionpolicy/test-ns/ai-eg-eep-envoy-ai-gateway-internal/extproc/0"}
2025-06-18 20:11:00.918Z 9:00 2025-06-18T11:11:00Z      INFO    envoy-gateway-extension-server  Added extproc-uds cluster to the list of clusters
2025-06-18 20:11:36.648Z 9:00 2025-06-18T11:11:36Z      INFO    controller.gateway-mutator      mutating gateway pod    {"pod_name": "", "pod_namespace": "envoy-gateway-system", "gateway_name": "envoy-ai-gateway-internal", "gateway_namespace": "test-ns"}
2025-06-19 10:48:39.498Z 9:00 2025-06-19T01:48:39Z      INFO    controller.ai-gateway-route     Reconciling AIGatewayRoute      {"namespace": "test-ns", "name": "llama3"}
2025-06-19 10:48:39.499Z 9:00 2025-06-19T01:48:39Z      INFO    controller.ai-gateway-route     syncing AIGatewayRoute  {"namespace": "test-ns", "name": "llama3"}
2025-06-19 10:48:39.499Z 9:00 2025-06-19T01:48:39Z      INFO    controller.ai-gateway-route     updating HTTPRoute      {"namespace": "test-ns", "name": "llama3"}
2025-06-19 10:48:39.523Z 9:00 2025-06-19T01:48:39Z      INFO    unknown field "spec.rules[1].name"      {"controller": "aigatewayroute", "controllerGroup": "aigateway.envoyproxy.io", "controllerKind": "AIGatewayRoute", "AIGatewayRoute": {"name":"llama3","namespace":"test-ns"}, "namespace": "test-ns", "name": "llama3", "reconcileID": "e8a88682-57db-405c-9013-13cae31039d8"}
2025-06-19 10:48:39.523Z 9:00 2025-06-19T01:48:39Z      INFO    controller.ai-gateway-route     syncing Gateway {"namespace": "test-ns", "name": "envoy-ai-gateway-internal"}
2025-06-19 10:48:39.543Z 9:00 2025-06-19T01:48:39Z      INFO    envoy-gateway-extension-server  non-ai-gateway cluster name     {"cluster_name": "envoyextensionpolicy/test-ns/ai-eg-eep-envoy-ai-gateway-internal/extproc/0"}
```

### PR DESCRIPTION
**Pull request by mathetake**
**Description**

This fixes a bug that the deletion event of AI Gateway resources were not propagated and reflected on the Gateway configuration. This changes the controller code so that it will add a finalizer and handle the deletion even gracefully.

**Related Issues/PRs (if applicable)**

Closes #728
Necessary for #836

### CODE REVIEW

File: internal/controller/gateway_test.go [hunk 1]
```diff
@@ -273,6 +273,13 @@ func TestGatewayController_bspToFilterAPIBackendAuth(t *testing.T) {
 				AzureCredentials: &aigv1a1.BackendSecurityPolicyAzureCredentials{},
 			},
 		},
+		{
```
Comment (mathetake) [inline internal/controller/gateway_test.go]: this is irrelevant but needed to increase the coverage ...

Comment (mathetake) [reply internal/controller/gateway_test.go]: https://github.com/envoyproxy/ai-gateway/pull/858

**Review by Xunzhuo — COMMENTED** [review]
Have we clean up the generated secrets as well as the generated epp?

**Comment by mathetake** [comment]
That's another topic than finalizer, and planning to work on it in a follow up PR

**Comment by Xunzhuo** [comment]
Yep, that's cool. I am thinking about adding e2e around deletion, make sure the lifecycle of resources is completed

**Comment by mathetake** [comment]
yep, we can do that but i think that controller-only e2e could be done in tests/controller as much as possible for testability/faster iteration

**Review by Xunzhuo — APPROVED** [review]
/lgtm
