### PR TITLE
extproc: account for parallel tool calls

### LINKED ISSUE #736: Add parallel tooling for AWS Bedrock
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Support multiple tool calls within the same response message for bedrock.

```
    MESSAGES_WITH_PARALLEL_TOOL_RESPONSE = [
        {
            "role": "user",
            "content": "What is the weather in Dallas, Texas and Orlando, Florida in Fahrenheit?",
        },
        {
            "role": "assistant",
            "tool_calls": [
                {
                    "id": "tool-1",
                    "type": "function",
                    "function": {
                        "name": WEATHER_TOOL["function"]["name"],
                        "arguments": '{"city": "Dallas", "state": "TX", '
                        '"unit": "fahrenheit"}',
                    },
                },
                {
                    "id": "tool-2",
                    "type": "function",
                    "function": {
                        "name": WEATHER_TOOL["function"]["name"],
                        "arguments": '{"city": "Orlando", "state": "Fl", '
                        '"unit": "fahrenheit"}',
                    },
                },
            ],
        },
        {
            "role": "tool",
            "tool_call_id": "tool-1`",
            "content": "The weather in Dallas TX is 88 degrees fahrenheit with mostly "
            "cloudy skies and a chance of rain in the evening.",
        },
        {
            "role": "tool",
            "tool_call_id": "tool-2",
            "content": "The weather in Orlando FL is 77 degrees fahrenheit with clear"
            "skies.",
        },
    ]
```

openai.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'ValidationException:http://internal.amazon.com/coral/com.amazon.bedrock/', 'code': '400', 'message': 'Expected toolResult blocks at messages.2.content for the following Ids: tool-2'}}

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

### PR DESCRIPTION
**Pull request by aabchoo**
**Description**
Resolves #736

Assistant that calls multiple tools are expected to group tool result in the same message. Adding logic for that!

### CODE REVIEW

**Comment by aabchoo** [comment]
edit: I think I will leave it to upstream to handle that

File: internal/extproc/translator/openai_awsbedrock.go [hunk 1]
```diff
@@ -405,7 +408,14 @@ func (o *openAIToAWSBedrockTranslatorV1ChatCompletion) openAIMessageToBedrockMes
 			if err != nil {
 				return err
 			}
-			bedrockReq.Messages = append(bedrockReq.Messages, bedrockMessage)
+
+			latestMessage := bedrockReq.Messages[len(bedrockReq.Messages)-1]
```
Comment (aabchoo) [inline internal/extproc/translator/openai_awsbedrock.go]: only concern here is if it's possible to send the tool messages before the assistant message

Comment (aabchoo) [reply internal/extproc/translator/openai_awsbedrock.go]: ie https://github.com/envoyproxy/ai-gateway/blob/main/internal/extproc/translator/openai_awsbedrock_test.go#L76-L101

Comment (yuzisun) [reply internal/extproc/translator/openai_awsbedrock.go]: The assistant message with tool_calls comes first, indicating the intention to use a tool, and then the tool message provides the result of that tool's execution. But there could be another assistant message with the tool results.

Comment (yuzisun) [reply internal/extproc/translator/openai_awsbedrock.go]: I think instead of using latestMessage, we can find the message with user role which has `ToolResult`, since we are merging to a single user role with tool results then it should only has one such message in the array.

Comment (aabchoo) [reply internal/extproc/translator/openai_awsbedrock.go]: All Tool messages are aggregated together? It's not aggregated with the tools  it's called with?

File: internal/extproc/translator/openai_awsbedrock.go [hunk 2]
```diff
@@ -405,10 +406,28 @@ func (o *openAIToAWSBedrockTranslatorV1ChatCompletion) openAIMessageToBedrockMes
 			if err != nil {
 				return err
 			}
+
+			for i+1 < openAIReqMessageLen {
```
Comment (yuzisun) [inline internal/extproc/translator/openai_awsbedrock.go:410]:
```suggestion
                         // Coalesce consecutive tool messages following a user message
			for i+1 < openAIReqMessageLen {
```

File: internal/extproc/translator/openai_awsbedrock.go [hunk 3]
```diff
@@ -405,10 +406,28 @@ func (o *openAIToAWSBedrockTranslatorV1ChatCompletion) openAIMessageToBedrockMes
...
+				nextMessage := &openAIReq.Messages[i+1]
+				if nextMessage.Type != openai.ChatMessageRoleTool {
+					break
+				}
+
+				nextToolMessage := nextMessage.Value.(openai.ChatCompletionToolMessageParam)
```
Comment (yuzisun) [inline internal/extproc/translator/openai_awsbedrock.go]: there is a type assertion risk here, consider using the "comma ok" idiom.

File: internal/extproc/translator/openai_awsbedrock.go [hunk 4]
```diff
@@ -405,10 +406,28 @@ func (o *openAIToAWSBedrockTranslatorV1ChatCompletion) openAIMessageToBedrockMes
...
+				nextBedrockMessage, err := o.openAIMessageToBedrockMessageRoleTool(&nextToolMessage, awsbedrock.ConversationRoleUser)
+				if err != nil {
+					return err
+				}
```
Comment (yuzisun) [inline internal/extproc/translator/openai_awsbedrock.go:423]: check the length of the content in case it is empty

**Review by yuzisun — APPROVED** [review]
