### PR TITLE
fix: route-scoped LLM request costs and add global defaults

### LINKED ISSUE #1688: Different CEL calculation formulas are used across multiple models.
_Description_:

I want to implement rate limiting based on usage costs in the Envoy AI Gateway.

I have two models with slightly different billing methods. I added a `metadataKey` to provide the billing metrics for the models.

This configuration does not achieve the desired effect. In the free model, the CEL seems to be using the CEL calculation formula of the other model.

## Sample：

I accessed the free GLM45 model, but I noticed in the response headers that the "billing_charges" quota was decreasing.

```
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-tke-glm45
  namespace: default
spec:
  llmRequestCosts:
    - metadataKey: llm_input_token
      type: InputToken
    - metadataKey: llm_output_token
      type: OutputToken
    - metadataKey: llm_total_token
      type: TotalToken
    - metadataKey: billing_charges
      type: CEL
      cel: "0"
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-tke-glm47
  namespace: default
spec:
  llmRequestCosts:
    - metadataKey: llm_input_token
      type: InputToken
    - metadataKey: llm_output_token
      type: OutputToken
    - metadataKey: llm_total_token
      type: TotalToken
    - metadataKey: billing_charges
      type: CEL
      cel: "int(double(input_tokens) / 1000.0 * 30.0 * 7.2 + double(output_tokens) / 1000.0 * 150.0 * 7.2)"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.envoyproxy.io/v1alpha1","kind":"BackendTrafficPolicy","metadata":{"annotations":{},"name":"envoy-ai-gateway-default","namespace":"default"},"spec":{"rateLimit":{"global":{"rules":[{"clientSelectors":[{"headers":[{"name":"x-user-id","type":"Distinct"}]}],"cost":{"request":{"from":"Number","number":0},"response":{"from":"Metadata","metadata":{"key":"billing_charges","namespace":"io.envoy.ai_gateway"}}},"limit":{"requests":100000,"unit":"Day"}},{"cost":{"request":{"from":"Number","number":0},"response":{"from":"Metadata","metadata":{"key":"billing_charges","namespace":"io.envoy.ai_gateway"}}},"limit":{"requests":1000000,"unit":"Day"}}]},"type":"Global"},"targetRefs":[{"group":"gateway.networking.k8s.io","kind":"Gateway","name":"envoy-ai-gateway-default"}]}}
  creationTimestamp: "2025-12-11T15:32:59Z"
  generation: 1
  name: envoy-ai-gateway-default
  namespace: default
  resourceVersion: "19951812"
  uid: b4986c34-cfe2-4758-afb0-10668815df71
spec:
  rateLimit:
    global:
      rules:
      - clientSelectors:
        - headers:
          - invert: false
            name: x-user-id
            type: Distinct
        cost:
          request:
            from: Number
            number: 0
          response:
            from: Metadata
            metadata:
              key: billing_charges
              namespace: io.envoy.ai_gateway
        limit:
          requests: 100000
          unit: Day
      - cost:
          request:
            from: Number
            number: 0
          response:
            from: Metadata
            metadata:
              key: billing_charges
              namespace: io.envoy.ai_gateway
        limit:
          requests: 1000000
          unit: Day
    type: Global
```

### PR DESCRIPTION
**Pull request by sukumargaonkar**
**Description**
This PR is an alternative to https://github.com/envoyproxy/ai-gateway/pull/1780 's implementation. It fixes pre-route LLMRequestCosts configuration, allowing different routes to use different CEL calculation formulas for the same metadataKey.

Previously even if a user configures different LLMRequestsCosts for each route with same metadataKey, the implementation would pick one of the LLMRequestsCosts and apply it globally to all the routes. this PR fixes that implementation

https://github.com/envoyproxy/ai-gateway/pull/1780 also implemented the same thing but by combining CEL expressions from all routes into a single CEL expression. this ran into CEL length limitations. This PR instead stores individual route-specific CELs in extproc's filterconfig and allows extrpoc to choose among them based on the route used by the current requests.

This PR also introduces GlobalLLMRequestCosts in GatewayConfig allowing to configure LLMRequestCosts that apply to all routes. during conflicts route-specific costs are prioritized over global costs.

**Breaking Change:**
This PR fixes the existing issue where if one ai-gateway route CR had LLMRequestCosts configured they will be applied to all route (even if they are not configured with it). After this PR is merged, costs will apply only to the route on which they are configured. Users can instead configure GatewayConfig.GlobalLLMRequestCosts to configure costs that apply to all routes.

**Related Issues/PRs (if applicable)**
Fixes: https://github.com/envoyproxy/ai-gateway/issues/1688
Related PR: https://github.com/envoyproxy/ai-gateway/pull/1780

### CODE REVIEW

File: internal/controller/gateway.go [hunk 1]
```diff
@@ -193,6 +200,63 @@ func bodyMutationToFilterAPI(m *aigv1b1.HTTPBodyMutation) *filterapi.HTTPBodyMut
...
+			return filterapi.GlobalLLMRequestCost{}, fmt.Errorf("invalid CEL expression: %w", err)
+		}
+		out.CEL = expr
+		return out, nil
+	default:
+		return filterapi.GlobalLLMRequestCost{}, fmt.Errorf("unknown request cost type: %s", cost.Type)
+	}
+}
+
+func aigwLLMRequestCostToFilterAPI(cost aigv1b1.LLMRequestCost, routeName string) (filterapi.LLMRequestCost, error) {
```
Comment (xiaolin593) [inline internal/controller/gateway.go:232]: two functions share pretty much same logic. can you refactor it to 
```suggestion
func validateAndExtractLLMRequestCost(cost aigv1b1.LLMRequestCost) (string, error) {
	switch cost.Type {
	case aigv1b1.LLMRequestCostTypeInputToken,
		aigv1b1.LLMRequestCostTypeCachedInputToken,
		aigv1b1.LLMRequestCostTypeCacheCreationInputToken,
		aigv1b1.LLMRequestCostTypeOutputToken,
		aigv1b1.LLMRequestCostTypeTotalToken:
		return "", nil

	case aigv1b1.LLMRequestCostTypeCEL:
		if cost.CEL == nil {
			return "", fmt.Errorf("missing CEL expression")
		}
		expr := *cost.CEL
		if _, err := llmcostcel.NewProgram(expr); err != nil {
			return "", fmt.Errorf("invalid CEL expression: %w", err)
		}
		return expr, nil

	default:
		return "", fmt.Errorf("unknown request cost type: %s", cost.Type)
	}
}

func aigwGlobalLLMRequestCostToFilterAPI(cost aigv1b1.LLMRequestCost) (filterapi.GlobalLLMRequestCost, error) {
	expr, err := validateAndExtractLLMRequestCost(cost)
	if err != nil {
		return filterapi.GlobalLLMRequestCost{}, err
	}

	out := filterapi.GlobalLLMRequestCost{
		MetadataKey: cost.MetadataKey,
		Type:        filterapi.LLMRequestCostType(cost.Type),
	}
	if cost.Type == aigv1b1.LLMRequestCostTypeCEL {
		out.CEL = expr
	}

	return out, nil
}

func aigwLLMRequestCostToFilterAPI(cost aigv1b1.LLMRequestCost, routeName string) (filterapi.LLMRequestCost, error) {
	expr, err := validateAndExtractLLMRequestCost(cost)
	if err != nil {
		return filterapi.LLMRequestCost{}, err
	}

	out := filterapi.LLMRequestCost{
		MetadataKey: cost.MetadataKey,
		RouteName:   routeName,
		Type:        filterapi.LLMRequestCostType(cost.Type),
	}
	if cost.Type == aigv1b1.LLMRequestCostTypeCEL {
		out.CEL = expr
	}

	return out, nil
}
```

File: internal/controller/gateway.go [hunk 2]
```diff
@@ -390,41 +470,25 @@ func (c *GatewayController) reconcileFilterConfigSecret(
...
-						return false, fmt.Errorf("invalid CEL expression: %w", err)
-					}
-					fc.CEL = expr
-				default:
-					return false, fmt.Errorf("unknown request cost type: %s", cost.Type)
+				fc, convErr := aigwLLMRequestCostToFilterAPI(cost, routeName)
+				if convErr != nil {
+					return false, fmt.Errorf("failed to convert LLMRequestCosts for route %s: %w", aiGatewayRoute.Name, convErr)
 				}
+				key := fc.MetadataKey + "\x00" + fc.RouteName
```
Comment (xiaolin593) [inline internal/controller/gateway.go:487]: what is `\x00` code here?

File: internal/extensionserver/post_translate_modify.go [hunk 3]
```diff
@@ -737,6 +747,68 @@ func (s *Server) isRouteGeneratedByAIGateway(route *routev3.Route) bool {
 	return false
 }
 
+func routeNameFromRouteConfigName(routeConfigName string) string {
+	// Envoy Gateway generated route config names follow:
+	// httproute/<namespace>/<name>/rule/<index>.
```
Comment (xiaolin593) [inline internal/extensionserver/post_translate_modify.go:752]:
```suggestion
	// httproute/<namespace>/<route_name>/rule/<index>.
```

File: internal/extproc/server.go [hunk 4]
```diff
@@ -377,6 +377,10 @@ func (s *Server) setBackend(ctx context.Context, p Processor, internalReqID stri
 	if err != nil {
 		return err
 	}
+	routeName, err := resolveRouteName(attributes)
+	if err != nil {
+		return err
+	}
```
Comment (xiaolin593) [inline internal/extproc/server.go:383]: resolveRouteName never returns error per implementation from line 427 to line 434.

File: tests/data-plane/testupstream_test.go [hunk 5]
```diff
@@ -53,7 +53,8 @@ func TestWithTestUpstream(t *testing.T) {
 
 	config := &filterapi.Config{
 		Version: version.Parse(),
-		LLMRequestCosts: []filterapi.LLMRequestCost{
+		// Dataplane Envoy does not set per-route xDS route_name metadata; use gateway defaults so costs still emit.
+		GlobalLLMRequestCosts: []filterapi.GlobalLLMRequestCost{
```
Comment (xiaolin593) [inline tests/data-plane/testupstream_test.go:57]: can we add a test case for route specific cost?

File: internal/internalapi/internalapi.go [hunk 6]
```diff
@@ -28,7 +28,7 @@ const (
 	// InternalMetadataBackendNameKey is the key used to store the backend name
 	InternalMetadataBackendNameKey = "per_route_rule_backend_name"
 	// InternalMetadataRouteNameKey is the key used to store the route name.
-	InternalMetadataRouteNameKey = "per_route_rule_route_name"
+	InternalMetadataRouteNameKey = "aigw_route_name"
```
Comment (xiaolin593) [inline internal/internalapi/internalapi.go:31]: 👍

**Review by yuzisun — APPROVED** [review]
