### PR TITLE
cli: fixes race during config writes on pre-startup

### LINKED ISSUE #1059: flake test: cmd/aigw.TestRun
```
2025-08-11T23:24:50.933Z	ERROR	config-loader	loader/configloader.go:50	failed to add config file to watcher	{"error": "\"/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/go-link-2413562533\": lstat /var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/go-link-2413562533: no such file or directory"}
Error: "/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/go-link-2413562533": lstat /var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/go-link-2413562533: no such file or directory
Usage:
  envoy-gateway server [flags]

Aliases:
  server, serve

Flags:
  -c, --config-path string   The path to the configuration file.
  -h, --help                 help for server

```

https://github.com/envoyproxy/ai-gateway/actions/runs/16890467146/job/47861612911?pr=1022

### PR DESCRIPTION
**Pull request by mathetake**
**Description**

Previously, there was a slight possibility that the config writes are not flushed by the time when EG starts running. This fixes it.

**Related Issues/PRs (if applicable)**
Closes #1059

### CODE REVIEW

**Comment by mathetake** [comment]
will run the CI multiple times before ready for review

**Comment by mathetake** [comment]
ok 14 times succeeded. 🤞

File: cmd/aigw/run.go [hunk 1]
```diff
@@ -100,7 +100,10 @@ func run(ctx context.Context, c cmdRun, stdout, stderr io.Writer) error {
 		return fmt.Errorf("failed to execute certgen: %w: %s", err, certGenOut.String())
 	}
 
-	tmpdir := os.TempDir()
+	tmpdir := filepath.Join(os.TempDir(), "aigw-run")
```
Comment (mathetake) [inline cmd/aigw/run.go:103]: this is also important and tangentially relevant; top level tmpdir can be troublesome (maybe only on macos)

**Review by Xunzhuo — APPROVED** [review]
