### PR TITLE
fix(controller): use server-side apply when patching finalizers

### LINKED ISSUE #1116: controller: do serverside apply on finalizer
*Description*:

There's a wip PR here https://github.com/envoyproxy/ai-gateway/pull/1088 but it seems some tests are failing, so it's missing something.

### PR DESCRIPTION
**Pull request by KaveeshKhattar**
**Description**

Switch to server-side apply via a new `patchFinalizersWithServerSideApply` helper. Server-side apply (SSA) does not require checking `resourceVersion`, so Kubernetes can merge the change even if there are concurrent modifications.

The helper does three things:
1. Looks up the GVK via `apiutil.GVKForObject`: required because controller-runtime strips TypeMeta when reading objects from the API, but SSA requires it to be set
2. Stamps the GVK back onto the object before patching
3. Patches using `client.RawPatch` with `types.ApplyPatchType`, `ForceOwnership`, and field owner `aigateway-controller`

**Related Issues/PRs (if applicable)**

Closes #1116
Related PR: #1088 

**Validation**

`make precommit test` passed locally.

**Special notes for reviewers (if applicable)**

This is my first PR to `envoyproxy/ai-gateway`, so I’m happy to iterate based on any feedback. Thanks!

### CODE REVIEW

File: internal/controller/controller.go [hunk 1]
```diff
@@ -523,9 +526,25 @@ func newConditions(conditionType, message string) []metav1.Condition {
 
 // aiGatewayControllerFinalizer is the name of the finalizer added to various AI Gateway resources.
 const aiGatewayControllerFinalizer = "aigateway.envoyproxy.io/finalizer"
+const aiGatewayControllerFieldOwner = "aigateway-controller"
+
+func patchFinalizersWithServerSideApply(ctx context.Context, c client.Client, o client.Object) error {
```
Comment (siddharth1036) [inline internal/controller/controller.go:533]: Should we use merge patch over SSA?

Comment (KaveeshKhattar) [reply internal/controller/controller.go:533]: I considered merge patch. The main reason I went with SSA is field ownership; SSA gives us managedFields semantics for the finalizer.

A merge patch is still a read‑modify‑write of the finalizers list and can overwrite concurrent changes without optimistic locking.

That said, if merge patch is preferred for simplicity, I can switch to it.

**Comment by mathetake** [comment]
Tests & format is failing. could you check locally first before pushing changes?
