### PR TITLE
fix: handles weight zero backendRef gracefully

### LINKED ISSUE #1664: Weights in aigatewayroutes set to 0 affects translation
_Description_:

We encountered an issue where setting weight of one backendRef to 0 results in translation failing in other backendRefs  within that rule.

Ie
```
  apiVersion: aigateway.envoyproxy.io/v1alpha1
  kind: AIGatewayRoute
  metadata:
    name: my-route
    namespace: default
  spec:
    rules:
    - matches:
      - headers:
        - name: ai-model
          value: gpt-4
      backendRefs:
      - name: gcp-backend-1
        weight: 0                  # ← Weight 0!
      - name: gcp-backend-2
        weight: 100
```

Seems the issue stems from how envoy gateway evaluates httproutes w/ weight 0.
https://github.com/envoyproxy/ai-gateway/blob/0a3ada44ecc73f04eb60e5a09aa8d2cd434e298c/internal/extensionserver/post_translate_modify.go#L210-L214

There is a mismatch where `cluster.LoadAssignment.Endpoints` == 1 and `httpRouteRule.BackendRefs` == 2. This results in the metadata not being set and to the upstream filter returning early.

I want to say it's related to https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/route.go#L1746-L1749

_Repro steps_:

1. Create a routing rule w/ 2 backend refs which requires translation
2. Set one of the weights to 0
3. Query route

_Logs_:

2025-12-16T21:16:51Z	INFO	envoy-gateway-extension-server	LoadAssignment endpoints length does not match backend refs length	{"cluster_name": "httproute/gateway/gcp.backend/rule/0", "endpoints_length": 1, "backend_refs_length": 2}

_Solution idea_:

Create a count for backendRef that do not have weights equal to 0.

### PR DESCRIPTION
**Pull request by mathetake**
**Description**

Envoy Gateway skips the weight zero backendRef when constructing localityLbEndoints slices. This starts handling such cases gracefully rather than taking them as errors.

**Related Issues/PRs (if applicable)**
Close #1664
Supersedes #1694

### CODE REVIEW

File: internal/extensionserver/post_translate_modify.go [hunk 1]
```diff
@@ -207,14 +207,16 @@ func (s *Server) maybeModifyCluster(cluster *clusterv3.Cluster) error {
...
-		if len(cluster.LoadAssignment.Endpoints) != len(httpRouteRule.BackendRefs) {
-			s.log.Info("LoadAssignment endpoints length does not match backend refs length",
-				"cluster_name", cluster.Name, "endpoints_length", len(cluster.LoadAssignment.Endpoints), "backend_refs_length", len(httpRouteRule.BackendRefs))
-			return nil
-		}
 		// Populate the metadata for each endpoint in the LoadAssignment.
-		for i, endpoints := range cluster.LoadAssignment.Endpoints {
-			backendRef := httpRouteRule.BackendRefs[i]
+		var lbEndpointIndex int
+		for i, backendRef := range httpRouteRule.BackendRefs {
```
Comment (aabchoo) [inline internal/extensionserver/post_translate_modify.go:212]: as a sanity check, is the `i` expected to be the lbEndpointIndex or backend ref index: https://github.com/envoyproxy/ai-gateway/blob/15080b001d3f4d92944828e08cd055900eed38dc/internal/extensionserver/post_translate_modify.go#L243C78-L243C96

Comment (mathetake) [reply internal/extensionserver/post_translate_modify.go:212]: yes and good catch anyways https://github.com/envoyproxy/ai-gateway/blob/15080b001d3f4d92944828e08cd055900eed38dc/internal/controller/gateway.go#L339-L342

**Review by aabchoo — APPROVED** [review]
