### PR TITLE
controller: fix watch resources that are created by the controller

### LINKED ISSUE #134: Delete HTTPRoute does not trigger reconciliation
If I manually delete underlying HTTPRoute resource owned by the `AIGatewayRoute`, the reconciliation is not triggered to recreate it.

### PR DESCRIPTION
**Pull request by sivanantha321**
Fixes #134

This PR makes the AIGatewayRoute controller to watch the resources that are created by it and trigger reconcilation.

### CODE REVIEW

**Comment by mathetake** [comment]
sorry i can't accept basically any fix without proper tests

**Comment by mathetake** [comment]
checking - are you up for writing test or we have to take this over

**Comment by sivanantha321** [comment]
> checking - are you up for writing test or we have to take this over

Yeah I can write a test for this.

**Comment by mathetake** [comment]
great, simple one would be enough

**Comment by sivanantha321** [comment]
@mathetake Added a test. Let me know if anything else needs to be done.

File: internal/controller/sink.go [hunk 1]
```diff
@@ -159,6 +160,10 @@ func (c *configSink) syncAIGatewayRoute(aiGatewayRoute *aigv1a1.AIGatewayRoute)
 			},
 			Spec: gwapiv1.HTTPRouteSpec{},
 		}
+		err := ctrlutil.SetControllerReference(aiGatewayRoute, &httpRoute, c.client.Scheme())
```
Comment (sivanantha321) [inline internal/controller/sink.go:163]: Should I remove the owner reference as we have controller reference ?

Comment (mathetake) [reply internal/controller/sink.go:163]: http route is not the only thing we create, so i think the change here will be a partial solution. so you could either delete this line or make changes to all resources not only the http route in this pr.

Comment (sivanantha321) [reply internal/controller/sink.go:163]: This is required for the fix to work, so i will update all other resources to use controller reference.

**Comment by sivanantha321** [comment]
@mathetake I noticed the controller creating HTTPRouteFilter without owner reference. I believe this because the resource is created per namespace. This resource is not watched by the controller. So If it gets deleted accidentally, It won't be recreated until the next reconcilation triggered by some other resource. The controller reference based approach used in this PR may not be appropriate for this resource.

**Comment by mathetake** [comment]
> the controller creating HTTPRouteFilter without owner reference. I believe this because the resource is created per namespace. 

yeah the HTTPRouteFilter is another issue for sure.

**Review by mathetake — APPROVED** [review]
excellent! thank you for working on this

**Comment by mathetake** [comment]
@sivanantha321 thank you for your contribution, nice work!
