### PR TITLE
fix: use internal id for routerProcessorsPerReqID map

### LINKED ISSUE #1340: aigateway extproc crash on setBackend
_Description_:
ai gateway extproc crashes on setbackend and requests are failing with 

```
upstream_connect_error_or_disconnect/reset_before_headers._reset_reason:_remote_connection_failure,_trans
port_failure_reason:_immediate_connect_error:_Connection_refused|remote_address:/etc/ai-gateway-extproc-uds/run.sock
```

_Repro steps_:
This might be caused by duplicated request ids sent by the user, after the first request route filter processor's defer is executed and the entry is deleted, but the second request was trying to use the same route filter processor as it gets the same processor from the `routerProcessorsPerReqID` map.

_Logs_:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x1800a09]

goroutine 16923 [running]:
github.com/envoyproxy/ai-gateway/internal/extproc.(*chatCompletionProcessorUpstreamFilter).SetBackend(0xc0006d48f0, {0x2147d18, 0xc000b26270}, 0xc00077f6d0, {0x21290c0, 0xc000155290}, {0x214fca0, 0xc000b60580})
	/home/runner/work/ai-gateway/ai-gateway/internal/extproc/chatcompletion_processor.go:468 +0x429
github.com/envoyproxy/ai-gateway/internal/extproc.(*Server).setBackend(0xc00036c3c0, {0x2147d18, 0xc000b26270}, {0x214fce0, 0xc0006d48f0}, {0xc001342288, 0x11}, 0x0, 0x1?)
	/home/runner/work/ai-gateway/ai-gateway/internal/extproc/server.go:326 +0x4a3
github.com/envoyproxy/ai-gateway/internal/extproc.(*Server).Process(0xc00036c3c0, {0x215d478, 0xc000e8c0b0})
	/home/runner/work/ai-gateway/ai-gateway/internal/extproc/server.go:203 +0x3df
github.com/envoyproxy/go-control-plane/envoy/service/ext_proc/v3._ExternalProcessor_Process_Handler({0x1cb3ec0?, 0xc00036c3c0}, {0x2158778, 0xc000814000})
	/home/runner/go/pkg/mod/github.com/envoyproxy/go-control-plane/envoy@v1.35.1-0.20250929230642-07d3df27ff4f/service/ext_proc/v3/external_processor_grpc.pb.go:106 +0xd8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000150200, {0x2147d18, 0xc000b26180}, 0xc000e000c0, 0xc000128b70, 0x3226f80, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.75.1/server.go:1722 +0x12f3
google.golang.org/grpc.(*Server).handleStream(0xc000150200, {0x2148cf0, 0xc00045e000}, 0xc000e000c0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.75.1/server.go:1846 +0xb54
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.75.1/server.go:1061 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 44
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.75.1/server.go:1072 +0x11d
```

### PR DESCRIPTION
**Pull request by yuzisun**
**Description**
The fix ensures that even if multiple requests arrive with identical x-request-id headers, they will have unique internal IDs in the `routerProcessorsPerReqID` map, preventing processor overwrites and incorrect cleanup.

**Related Issues/PRs (if applicable)**
Fixes #1340 

**Special notes for reviewers (if applicable)**
  - Created internal request ID header constant: Added internalReqIDHeader = "x-ai-eg-internal-req-id"
  - Modified request ID generation logic:
     - Router filter: Creates unique internal request ID by appending UUID suffix: `originalReqID + "-" + uuid.NewString()`
     - Upstream filter: Uses the internal request ID passed from router filter via header

### CODE REVIEW

**Comment by yuzisun** [comment]
> so the change itself should be fine, so i will stamp once the tests passing, but i wonder when exactly this happens though

two requests with identical request id got processed concurrently like following 
```
kubectl logs envoy-gateway-bc2ff25f-tznwv  -n gateway-system -c ai-gateway-extproc --previous| grep "request headers processed\" request_id=prompt-with-image is_upstream_filter=false"
time=2025-10-12T14:10:59.740Z level=DEBUG msg="request headers processed" request_id=prompt-with-image is_upstream_filter=false response=request_headers:{}
time=2025-10-12T14:11:01.890Z level=DEBUG msg="request headers processed" request_id=prompt-with-image is_upstream_filter=false response=request_headers:{}
time=2025-10-12T14:11:01.934Z level=DEBUG msg="request headers processed" request_id=prompt-with-image is_upstream_filter=false response=request_headers:{}
```

**Comment by mathetake** [comment]
The test failure looks legit ..

**Comment by aabchoo** [comment]
Going to take over this PR per request  (no pun intended) and figure out what's happening 🙇

File: internal/extproc/server.go [hunk 1]
```diff
@@ -177,9 +183,26 @@ func (s *Server) Process(stream extprocv3.ExternalProcessor_ProcessServer) error
...
+				}
+			} else {
+				// For router filter, create a unique internal request ID to avoid race conditions
+				// with duplicate x-request-id values by appending a UUID suffix to the original request ID
+				internalReqID = originalReqID + "-" + uuid.NewString()
+
+				// Ctx will only contain the value for testing purposes
+				if testInternalReqID, ok := ctx.Value(internalReqIDHeader).(string); ok {
+					internalReqID = testInternalReqID
+				}
```
Comment (mathetake) [inline internal/extproc/server.go]: instead of this code, i would suggest to add `uuidFn func() string` to the server struct and make it configured on the test to get the deterministic result

File: internal/extproc/server_test.go
Comment (mathetake) [inline internal/extproc/server_test.go]: maybe put "x-request-id: original-req-id" to clarify what's the expected set-header value below?

File: internal/extproc/server.go (hunk 1 above)
Comment (aabchoo) [reply internal/extproc/server.go]: thanks for the suggestion
